### ISSUE TITLE
OS X 10.11 and "ld: library not found for -lgcc_s.10.4"

### ISSUE THREAD

**Issue by DominusExult** [devernay/xcodelegacy#15] opened 2015-10-01 22:37 UTC
Hi,
Seems to me that certain things are having problems. Not sure exactly what is up but I struggled to compile freetype-2.6 for ppc. First configure bailed with this message. After editing the right configure so it wouldn't bail, I was able to run make for a bit until it stumbled again over this error.
Not much out there yet about this error but it seems some weird error related to El Capitan...

**Comment by devernay** [comment] 2015-10-02 07:01
Can you please give the configure line you used for freetype?
And extract the failure line from configure.log?
Do you have "-mmacosx-version-min=10.4 -isysroot /Developer/SDKs/MacOSX10.4u.sdk" in your CFLAGS and LDFLAGS?
Can you also give the output of "ls -l /Developer/SDKs/MacOSX10.4u.sdk/usr/lib/libgcc_s.10.4.dylib"

**Comment by DominusExult** [comment] 2015-10-02 09:21
./configure --host=powerpc-apple-darwin --without-bzip2 --without-harfbuzz --with-png --with-zlib --with-old-mac-fonts
I have "-mmacosx-version-min=10.4 -isysroot /Developer/SDKs/MacOSX10.5.sdk" in my CFLAGS and LDFLAGS and export MACOSX_DEPLOYMENT_TARGET=10.4 as well. (same error with the 10.4u.sdk)

Dominus$ ls -l /developer/SDKs/MacOSX10.4u.sdk/usr/lib/libgcc_s.10.4.dylib
-rwxr-xr-x  1 root  wheel  41500 20 Apr  2007 /developer/SDKs/MacOSX10.4u.sdk/usr/lib/libgcc_s.10.4.dylib*

Dominus$ ls -l /developer/SDKs/MacOSX10.5.sdk/usr/lib/libgcc_s.10.4.dylib
-rw-r--r--  1 root  wheel  33256 19 Feb  2008 /developer/SDKs/MacOSX10.5.sdk/usr/lib/libgcc_s.10.4.dylib

The error happens in builds/unix/configure of freetype:
```
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for suffix of native executables" >&5
$as_echo_n "checking for suffix of native executables... " >&6; }
  rm -f a.* b.* a_out.exe conftest.*
  echo > conftest.c "int main() { return 0;}"
  ${CC_BUILD} conftest.c || as_fn_error $? "native C compiler is not working" "$LINENO" 5
```
Error:
```
checking for suffix of native executables... ld: library not found for -lgcc_s.10.4
collect2: ld returned 1 exit status
configure: error: native C compiler is not working
make: *** [setup] Error 1
```

I don't know why it looks for the dylib in /usr/lib/ but there Xcode 7 replaced those dylibs with tld files. If I copy the two dylibs from the 10.6 or 10.5 sdk "back" into /usr/local/lib everything works.
So probably my biggest problem is why it looks in /usr/lib instead of /developer/SDKs/MacOSX.10.5.sdk/usr/lib...

**Comment by devernay** [comment] 2015-10-02 16:11
the problem is perhaps with freetype's configure, which probably doesn't use the right flags.

did you try compiling that simple program manually:
> int main() { return 0;}
can you send the relevant portion of config.log?

**Comment by devernay** [comment] 2015-11-11 15:07
closing, probably a freetype compilation issue

**Closed by devernay** 2015-11-11 15:07 UTC
